In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
label_encoder_gender= LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [4]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [5]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [9]:
# SAve the encoders & scalers for later use.
with open('label_encoder_gender1.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo1.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [10]:

x_train, x_test, y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
with open('scaler1.pkl','wb') as file:
    pickle.dump(scaler,file)

In [11]:
## Train our ANN with regression

## ANN Regression Problem Statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1774431362.263876  422431 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1774431363.365962  422431 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1774431369.965631  422431 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [ ]:
model=Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression.
    # When we don't apply any activation function, it uses the default one i.e. linear activation function

])

# compile the model. For mored
model.compile(optimizer='adam', loss='mean_absolute_error',metrics=['mae'])
model.summary()

/home/vwagh/git/udemy/project/churn_modelling/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1774431372.505919  422431 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir= "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H:%M:%S")
tensorboard_callback=TensorBoard(log_dir=log_dir)

In [15]:
# Setup Early stopping
earlyStopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
#Train the model

history=model.fit(
    x_train, y_train,
    validation_data=(x_test,y_test),
    epochs=100,
    callbacks=[earlyStopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 100371.6250 - mae: 100371.6250 - val_loss: 98488.0156 - val_mae: 98488.0156
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 99496.2734 - mae: 99496.2734 - val_loss: 96701.6875 - val_mae: 96701.6875
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 96384.4297 - mae: 96384.4297 - val_loss: 92145.6406 - val_mae: 92145.6406
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 90340.6016 - mae: 90340.6016 - val_loss: 84710.1250 - val_mae: 84710.1250
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 81688.1719 - mae: 81688.1719 - val_loss: 75369.7812 - val_mae: 75369.7812
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 71883.0781 - mae: 71883.0781 - val_loss: 66147.4531 - val_mae: 66147.4531
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 63008.8242 - mae: 63008.8242 - val_loss: 58773.0781 - val_mae: 58773.0781
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 56559.2344 - mae: 56559.2344 - val_loss: 54031.5000 - val_mae: 54031.5000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 52874.9102 - mae: 52874.9102 - val_loss: 51847.2344 - val_mae: 51847.2344
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 51183.7266 - mae: 51183.7266 - val_loss: 51086.7227 - val_mae: 51086.7227
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50548.2070 - mae: 50548.2070 - val_loss: 50832.9805 - val_mae: 50832.9805
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50308.9805 - mae: 50308.9805 - val_loss: 50722.5781 - val_mae: 50722.5781
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50195.8320 - mae: 50195.8320 - val_loss: 50657.3750 - val_mae: 50657.3750
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50120.5625 - mae: 50120.5625 - val_loss: 50600.6523 - val_mae: 50600.6523
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50062.3047 - mae: 50062.3047 - val_loss: 50552.9453 - val_mae: 50552.9453
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50019.0117 - mae: 50019.0117 - val_loss: 50510.4609 - val_mae: 50510.4609
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49973.2969 - mae: 49973.2969 - val_loss: 50475.3828 - val_mae: 50475.3828
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49936.9297 - mae: 49936.9297 - val_loss: 50453.8359 - val_mae: 50453.8359
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49905.5312 - mae: 49905.5312 - val_loss: 50438.5430 - val_mae: 50438.5430
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49877.4258 - mae: 49877.4258 - val_loss: 50415.2109 - val_mae: 50415.2109
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49851.4141 - mae: 49851.4141 - val_loss: 50402.4688 - val_mae: 50402.4688
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49825.8750 - mae: 49825.8750 - val_loss: 50374.1953 - val_mae: 50374.1953
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49805.9141 - mae: 49805.9141 - val_loss: 50362.9375 - val_mae: 50362.9375
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49781.0195 - mae: 49781.0195 - val_loss: 50351.0781 - val_mae: 50351.0781
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49761.1289 - mae: 49761.1289 - val_loss: 50339.3789 - val_mae: 50339.3789
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49744.4805 - mae: 49744.4805 - val_loss: 50326.2383 - val_mae: 50326.2383
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49724.2070 - mae: 49724.2070 - val_loss: 50326.0742 - val_mae: 50326.0742
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49708.9531 - mae: 49708.9531 - val_loss: 50316.2188 - val_mae: 50316.2188
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49694.7148 - mae: 49694.7148 - val_loss: 50310.5391 - val_mae: 50310.5391
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49677.8047 - mae: 49677.8047 - val_loss: 50307.3398 - val_mae: 50307.3398
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49662.8359 - mae: 49662.8359 - val_loss: 50297.0938 - val_mae: 50297.0938
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49651.0664 - mae: 49651.0664 - val_loss: 50291.5430 - val_mae: 50291.5430
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49635.3750 - mae: 49635.3750 - val_loss: 50292.0234 - val_mae: 50292.0234
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 49626.0469 - mae: 49626.0469 - val_loss: 50290.8242 - val_mae: 50290.8242
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 49613.4570 - mae: 49613.4570 - val_loss: 50278.3320 - val_mae: 50278.3320
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49602.0430 - mae: 49602.0430 - val_loss: 50290.9375 - val_mae: 50290.9375
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 49591.8398 - mae: 49591.8398 - val_loss: 50286.5742 - val_mae: 50286.5742
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49578.7070 - mae: 49578.7070 - val_loss: 50280.0391 - val_mae: 50280.0391
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49573.9609 - mae: 49573.9609 - val_loss: 50285.6602 - val_mae: 50285.6602
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49562.8555 - mae: 49562.8555 - val_loss: 50275.5078 - val_mae: 50275.5078
Epoch 41/100
130/250 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 48893.7381 - mae: 48893.7381

In [ ]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
%tensorboard --logdir regrationlogs/fit

Reusing TensorBoard on port 6007 (pid 94683), started 0:01:06 ago. (Use '!kill 94683' to kill it.)